SELECT "kuala-lumpur"."outlets".* FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" = 11383 AND "kuala-lumpur"."outlets"."status" = 0 ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets"."name" FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" = 100570 ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets"."id" FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" = 105803 ORDER BY outlets.order ASC, outlets.id ASC;

SELECT COUNT(*) FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" = 99591;

SELECT "kuala-lumpur"."eagle_activities".* FROM "kuala-lumpur"."eagle_activities" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."eagle_activities"."id" = "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" WHERE "kuala-lumpur"."eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."outlet_id" = 11516 AND "kuala-lumpur"."eagle_activities"."status" = 0;

SELECT COUNT(*) FROM "kuala-lumpur"."eagle_activities" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."eagle_activities"."id" = "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" WHERE "kuala-lumpur"."eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."outlet_id" = 2375 AND "kuala-lumpur"."eagle_activities"."status" = 0 AND "kuala-lumpur"."eagle_activities"."listing_type" = 1;

-- SHell SQL
SELECT "kuala-lumpur"."outlets".* FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" in (SELECT random_between(62624, 64250)) AND "kuala-lumpur"."outlets"."status" = 0 ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets".* FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" in (SELECT random_between(61891, 61900)) AND "kuala-lumpur"."outlets"."status" = 0 ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets"."name" FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" IN (SELECT random_between(62624, 64250)) ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets"."name" FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" IN (SELECT random_between(61891, 61900)) ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets"."id" FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" IN (SELECT random_between(62624, 64250)) ORDER BY outlets.order ASC, outlets.id ASC;

SELECT "kuala-lumpur"."outlets"."id" FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" IN (SELECT random_between(61891, 61900)) ORDER BY outlets.order ASC, outlets.id ASC;

SELECT COUNT(*) FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" IN (SELECT random_between(62624, 64250));

SELECT COUNT(*) FROM "kuala-lumpur"."outlets" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."outlets"."id" = "kuala-lumpur"."outlet_eagle_activities"."outlet_id" WHERE "kuala-lumpur"."outlets"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" IN (SELECT random_between(61891, 61900));

SELECT COUNT(*) FROM "kuala-lumpur"."eagle_activities" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."eagle_activities"."id" = "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" WHERE "kuala-lumpur"."eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."outlet_id" IN (SELECT random_between(19817, 20739));

SELECT COUNT(*) FROM "kuala-lumpur"."eagle_activities" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."eagle_activities"."id" = "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" WHERE "kuala-lumpur"."eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."outlet_id" IN (SELECT random_between(22289, 23305));

SELECT "kuala-lumpur"."eagle_activities".* FROM "kuala-lumpur"."eagle_activities" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."eagle_activities"."id" = "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" WHERE "kuala-lumpur"."eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."outlet_id" IN (SELECT random_between(19817, 20739)) AND "kuala-lumpur"."eagle_activities"."status" IN (SELECT random_between(0, 2));

SELECT "kuala-lumpur"."eagle_activities".* FROM "kuala-lumpur"."eagle_activities" INNER JOIN "kuala-lumpur"."outlet_eagle_activities" ON "kuala-lumpur"."eagle_activities"."id" = "kuala-lumpur"."outlet_eagle_activities"."eagle_activity_id" WHERE "kuala-lumpur"."eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."deleted_at" IS NULL AND "kuala-lumpur"."outlet_eagle_activities"."outlet_id" IN (SELECT random_between(22289, 23305)) AND "kuala-lumpur"."eagle_activities"."status" IN (SELECT random_between(0, 2));